# Generated by Django 5.1.2 on 2024-10-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimage', models.ImageField(blank=True, default='', upload_to='media/store/images/thumbimages')),
                ('carname', models.CharField(max_length=20)),
                ('carrent', models.IntegerField()),
                ('carpdf', models.FileField(blank=True, default='', upload_to='media/store/pdfs')),
            ],
        ),
    ]
